name: "Action test 101"
description: "A Github Action that I will test for doing a lot cool stuffs"
inputs:
  num:
    description: "Enter a number"
    required: true
    default: "1"
outputs:
  num_squared:
    description: "Square of a input"
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using:: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to shell
      run: |
        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the numbers' square
      id: get-square
      runs: python src/get_num_square.py
      shell: bash
